### ISSUE TITLE
Add TicTrainer output scoring

### ISSUE THREAD

**Issue by jonkoller** [BlackHershey/newtics_clinical#1]
We need to add scoring for the TicTrainer (Zoom) output files to score_drz.py.

**Input:**
1. TicTrainer output files (ATTACH EXAMPLE)

**Output:**
1. number of tics observed in 5-minute session
2. number of 10-second-long tic-free intervals

**Also check** the comments, drz_tics_1st_bselne, drz_tics_aftr_1st_bselne, drz_tics_bf_bselne fields and where they come from (REDCap or the _tics.txt files).

**Comment by jonkoller** [comment]
@KBMD Can you please attach an example TicTrainer output file to this issue?

**Comment by KBMD** [comment]
It's already there at the bottom of each file


Kevin J. Black
